# Generated by Django 4.2.1 on 2023-05-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, verbose_name='Registrant Business Name')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Registrant City')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Registrant Contact Person')),
                ('phone_number', models.CharField(blank=True, max_length=100, verbose_name='Registrant Phone Number')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Registrant Email')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Registrant Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrant Application Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrant Application Update Date')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Registrant Application Acceptance Status')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='Registrant Application Dismissal Status')),
                ('is_mail_sent', models.BooleanField(default=False, verbose_name='Registrant Application Mail Sent Status')),
            ],
            options={
                'verbose_name': 'Registrant Application',
                'verbose_name_plural': 'Registrant Applications',
            },
        ),
    ]
