# Generated by Django 4.1.3 on 2023-05-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register_application',
            options={'verbose_name': 'Registrant Application', 'verbose_name_plural': 'Registrant Applications'},
        ),
        migrations.AddField(
            model_name='register_application',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register_application',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
