# Generated by Django 4.1.3 on 2023-05-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmanager', '0002_alter_register_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
