# Generated by Django 4.1.3 on 2023-05-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmanager', '0003_alter_register_application_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_application',
            name='is_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
