# Generated by Django 4.1.3 on 2023-05-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmanager', '0004_register_application_is_mail_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_application',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Registrant Address'),
        ),
        migrations.AlterField(
            model_name='register_application',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Registrant Business Name'),
        ),
        migrations.AlterField(
            model_name='register_application',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Registrant City'),
        ),
        migrations.AlterField(
            model_name='register_application',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Registrant Contact Person'),
        ),
        migrations.AlterField(
            model_name='register_application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrant Application Date'),
        ),
        migrations.AlterField(
            model_name='register_application',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Registrant Email'),
        ),
        migrations.AlterField(
            model_name='register_application',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Registrant Application Acceptance Status'),
        ),
        migrations.AlterField(
            model_name='register_application',
            name='is_dismissed',
            field=models.BooleanField(default=False, verbose_name='Registrant Application Dismissal Status'),
        ),
        migrations.AlterField(
            model_name='register_application',
            name='is_mail_sent',
            field=models.BooleanField(default=False, verbose_name='Registrant Application Mail Sent Status'),
        ),
        migrations.AlterField(
            model_name='register_application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Registrant Phone Number'),
        ),
        migrations.AlterField(
            model_name='register_application',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registrant Application Update Date'),
        ),
    ]
