# Generated by Django 4.2.1 on 2023-05-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_shipped',
            field=models.IntegerField(default=1, verbose_name='1 box contains in kg'),
        ),
    ]
