# Generated by Django 4.2.1 on 2023-05-22 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_product_quantity_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sweden_organization_number',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Sweden Organization Number VAT NMMER'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Account', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
