# Generated by Django 4.1.3 on 2023-05-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity_ordered',
            new_name='quantity',
        ),
    ]
