# Generated by Django 4.1.3 on 2023-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
