# Generated by Django 4.1.3 on 2023-05-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
