# Generated by Django 4.1.3 on 2023-05-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_mail_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mail_sent',
        ),
    ]
