# Generated by Django 4.1.3 on 2023-05-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
