# Generated by Django 4.1.3 on 2023-05-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_mail_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='mail_sent',
            new_name='is_mail_sent',
        ),
    ]
