# Generated by Django 4.1.3 on 2023-05-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_mail_sent_order_is_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mail_status',
            field=models.BooleanField(default=True),
        ),
    ]
