# Generated by Django 4.1.3 on 2023-05-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_total',
            new_name='total_price',
        ),
    ]
