# Generated by Django 4.1.3 on 2023-05-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_order_total_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
